export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUBMITTING = 'SEARCH_SUBMITTING';
export const SEARCH_SUCCESSFUL = 'SEARCH_SUCCESSFUL';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const MODAL_EDIT_ROW = 'MODAL_EDIT_ROW';
export const MODAL_SUBMIT_EDIT = 'MODAL_SUBMIT_EDIT';
export const MODAL_CREATE_ROW = 'MODAL_CREATE_ROW';
export const MODAL_SUBMIT_CREATE = 'MODAL_VIEW_ROW';
export const MODAL_VIEW_ROW = 'MODAL_VIEW_ROW';
