export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUBMITTING = 'SEARCH_SUBMITTING';
export const SEARCH_SUCCESSFUL = 'SEARCH_SUCCESSFUL';
export const SEARCH_FAILED = 'SEARCH_FAILED';
